apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmaptestapp
spec:
  selector:
    matchLabels:
      app: configmaptestapp
  replicas: 1
  template:
    metadata:
      labels:
        app: configmaptestapp
    spec:
      containers:
      - name: configmaptestapp
        image: abhirockzz/configmaptestapp
        volumeMounts:
        - mountPath: /config
          name: appconfig-data-volume
        ports:
        - containerPort: 8080
      volumes:
        - name: appconfig-data-volume
          configMap:
            name: app-config